apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-credentials-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-credentials
  template:
    metadata:
      labels:
        app: postgres-credentials
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      containers:
        - name: postgres
          image: postgres:16.3
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgres-credentials/data
              name: postgres-credentials
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-credentials-config
                  key: POSTGRES_DB
          readinessProbe:
            exec:
              command: ["pg_isready"]
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 5
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      volumes:
        - name: postgres-credentials
          persistentVolumeClaim:
            claimName: postgres-credentials-volume-claim