apiVersion: v1
kind: Service
metadata:
  name: postgres-credentials
spec:
  selector:
    app: postgres-credentials
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP