apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-credentials-volume-claim
  labels:
    app: postgres-credentials
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi