apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-gql-volume-claim
  labels:
    app: postgres-gql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 70Gi