{
 "title": "UOIS Dashboard",
 "description": "Revize: 15/06/2025 18:30",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Virtual Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "{{instance}}({{job}})" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{instance}}({{job}})" }
   ]
  },
  {
   "title": "Garbage collect(10m)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Objects" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(python_gc_collections_total[10m])",
     "legendFormat": "{{instance}}({{job}}, gen{{generation}} )"
    }
   ]
  },
  {
   "title": "Uncollectable Objects(1h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "expr": "increase(python_gc_objects_uncollectable_total[1h])",
     "legendFormat": "gen{{generation}}"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total [$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU - Open File descriptors",
   "type": "timeseries",
   "description": "Number of open descriptors relative to max number",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "/ 1024 " } },
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Latency 95th %",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (handler, le)(frontnend_http_request_duration_seconds_bucket{handler=\"/api/gql\"}))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "frontnend_http_request_size_bytes_sum / frontnend_http_request_size_bytes_count\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "frontnend_http_response_size_bytes_sum / frontnend_http_response_size_bytes_count\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG request size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(rate(frontnend_http_request_size_bytes_sum[10m])\r\n/\r\nrate(frontnend_http_request_size_bytes_count[10m])>0)",
     "legendFormat": "{{instance}}-{{job}} : ({{method}} {{status}})"
    }
   ]
  }
 ]
}