apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
type: Opaque
stringData:
  SALT: fe1c71b2-74c0-41e5-978f-eecbffac7418
  ADMIN_DEFAULT_EMAIL: john.newbie@world.com
  ADMIN_DEFAULT_PASSWORD: john.newbie@world.com