apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-volume-claim
  labels:
    app: prometheus
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi