name: "Lint Dockerfiles"

on:
  push:
    # Trigger on changes to Dockerfile or any docker-compose*.yml
    #branches: [ latest ]
    branches: [ pipelines ]
    paths:
      - 'Dockerfile'
      - 'docker-compose*.yml'
  pull_request:
    # Trigger on PRs that change Dockerfile or any docker-compose*.yml
    #branches: [ latest ]
    branches: [ pipelines ]
    paths:
      - 'Dockerfile'
      - 'docker-compose*.yml'

jobs:
  lint-docker:
    name: "Dockerfile & docker-compose Lint"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint Dockerfile with hadolint
        run: |
          echo "Linting Dockerfile..."
          # Use the official hadolint image to lint the Dockerfile via stdin
          docker run --rm -i hadolint/hadolint < Dockerfile

      - name: Validate docker-compose files
        run: |
          echo "Searching for docker-compose files..."
          # Find all files matching the pattern docker-compose*.yml
          FILES=$(ls docker-compose*.yml 2>/dev/null || true)
          if [ -z "$FILES" ]; then
            echo "No docker-compose files found, skipping this step."
            exit 0
          fi

          # For each found file, run 'docker-compose config --quiet' to validate syntax
          for FILE in $FILES; do
            echo "Linting $FILE..."
            docker-compose -f "$FILE" config --quiet
            echo "$FILE is valid."
          done
