# .github/workflows/graphql-smoke-tests.yml
name: CI - GraphQL Smoke Tests (OAuth2 login)

on:
  push:
    branches: [ pipelines ]
  pull_request:
    branches: [ pipelines ]

jobs:
  get-jwt:
    name: Get JWT Token
    runs-on: ubuntu-latest

    env:
      TZ: Europe/Prague
      DEMO_EMAIL: john.newbie@world.com
      DEMO_PASSWORD: john.newbie@world.com

    outputs:
      jwt: ${{ steps.extract_jwt.outputs.jwt }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start Docker Compose stack
        run: |
          echo "==> Spouštím Docker Compose stack na pozadí..."
          docker compose -f docker-compose.hk2025.yml up -d --build

      - name: Wait for services to be healthy
        run: |
          echo "Čekám 30 sekund, aby služby absolvovaly healthcheck..."
          sleep 30

      - name: Perform OAuth2 login (get session cookie and extract JWT)
        id: extract_jwt
        run: |
          echo "==> 1) STAHUJI login stránku (pro získání 'key' a počáteční cookie)…"
          COOKIE_INIT="cookie_init.txt"
          LOGIN_HTML="login.html"
          LOGIN_URL="http://localhost:33001/oauth/login2?redirect_uri=/"

          # 1. Stáhnout login formulář (GET) a uložit cookie_init.txt + login.html
          curl -s -L "$LOGIN_URL" \
            -c "$COOKIE_INIT" \
            -o "$LOGIN_HTML"

          # 2. Ze staženého HTML vyextrahovat hodnotu skrytého pole 'key'
          echo "==> 2) EXTRAHUJI 'key' ze staženého HTML…"
          KEY=$(grep -oP 'name="key".*?value=\K[^ >]+' "$LOGIN_HTML" || true)
          if [ -z "$KEY" ]; then
            echo "❌ Chyba: Nepodařilo se najít hodnotu 'key' v $LOGIN_HTML!"
            exit 1
          fi
          echo "→ Nalezen KEY: $KEY"

          # 3. Provedu POST přihlášení (username + password + key); nové cookie se uloží do cookies.txt
          echo "==> 3) POSÍLÁM POST s přihlášením…"
          COOKIE_JAR="cookies.txt"
          curl -s -L "$LOGIN_URL" \
            -b "$COOKIE_INIT" \
            -c "$COOKIE_JAR" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "username=${{ env.DEMO_EMAIL }}" \
            -d "password=${{ env.DEMO_PASSWORD }}" \
            -d "key=${KEY}" \
            -o /dev/null

          # Ověření, že cookies.txt není prázdný
          if [ ! -s "$COOKIE_JAR" ]; then
            echo "❌ Chyba: Nepodařilo se uložit cookie do $COOKIE_JAR."
            exit 1
          fi

          # 4. Extrahovat JWT z cookie 'authorization'
          JWT=$(grep -i -E "localhost.*authorization" "$COOKIE_JAR" | awk '{print $7}')
          if [ -z "$JWT" ]; then
            echo "❌ Chyba: V cookie-jar nebyla nalezena hodnota 'authorization'!"
            exit 1
          fi

          # Uložit JWT jako výstup kroku
          echo "jwt=$JWT" >> $GITHUB_OUTPUT
          echo "✅ JWT token úspěšně získán a uložen jako job output."
        shell: bash

      - name: Tear down Docker Compose stack
        if: always()
        run: |
          echo "==> Clean up: Ukončuji Docker Compose stack…"
          docker compose -f docker-compose.hk2025.yml down --volumes
        shell: bash

  introspection:
    name: GraphQL Introspection (using stored JWT)
    runs-on: ubuntu-latest
    needs: [get-jwt]

    env:
      TZ: Europe/Prague
      JWT_TOKEN: ${{ needs.get-jwt.outputs.jwt }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start Docker Compose stack
        run: |
          echo "==> Spouštím Docker Compose stack na pozadí..."
          docker compose -f docker-compose.hk2025.yml up -d --build

      - name: Wait for services to be healthy
        run: |
          echo "Čekám 30 sekund, aby služby absolvovaly healthcheck..."
          sleep 30

      - name: HEAD request on GraphQL endpoint with Bearer token
        run: |
          echo "Používám JWT: $JWT_TOKEN"
          HTTP_STATUS=$(
            curl -s -o /dev/null -w "%{http_code}" \
              -H "Authorization: Bearer $JWT_TOKEN" \
              http://localhost:33001/api/gql -X HEAD
          )
          echo "HTTP status: $HTTP_STATUS"
          if [[ "$HTTP_STATUS" != "200" && "$HTTP_STATUS" != "400" && "$HTTP_STATUS" != "405" ]]; then
            echo "❌ Neočekávaný status $HTTP_STATUS"
            exit 1
          fi
          echo "✅ HEAD request úspěšný (status $HTTP_STATUS)."
        shell: bash

      - name: Perform GraphQL Introspection Query
        id: introspect
        run: |
          echo "==> Provedení introspekčního dotazu na /api/gql s Bearer tokenem…"
          INTROSPECTION_QUERY='{"query":"{ __schema { types { name } } }"}'
          RESPONSE=$(
            curl -s -X POST http://localhost:33001/api/gql \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $JWT_TOKEN" \
              -d "$INTROSPECTION_QUERY"
          )

          echo "=== Introspection response: ==="
          echo "$RESPONSE"

          echo "$RESPONSE" | grep '"__schema"' \
            && echo "✅ Introspection OK - nalezen klíč __schema." \
            || (echo "❌ Introspection selhala - nenalezen klíč __schema." && exit 1)
        shell: bash

      - name: Tear down Docker Compose stack
        if: always()
        run: |
          echo "==> Clean up: Ukončuji Docker Compose stack…"
          docker compose -f docker-compose.hk2025.yml down --volumes
        shell: bash
