name: HTTP Smoke Tests
#* works
on:
  # push:
  #   #branches: [ latest ]
#    branches: [ main ]
  pull_request:
    #branches: [ latest ]
    branches: [ main ]
    
jobs:
  http-smoke:
    name: HTTP Smoke Tests (single port 33001)
    runs-on: ubuntu-latest

    env:
      TZ: Europe/Prague

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start Docker Compose stack
        run: docker compose -f docker-compose.hk2025.yml up -d --build
        
        # no need for more than 30s, cuz the index is loaded fast
      - name: Wait for frontend and subsystems
        run: sleep 30

      - name: Check running containers
        run: docker ps -a

      - name: Verify HTTP 200 on all service URLs
        run: |
          set -e
          echo "Verifying availability of each URL (expecting HTTP 200)..."
          SERVICES=(
            "index"
            "ug"
            "lessons"
            "projects"
            "events"
            "surveys"
            "facilities"
            "granting"
            "forms"
            "publications"
            "users"
          )
          for S in "${SERVICES[@]}"; do
            URL="http://localhost:33001/${S}/"
            echo -n "  → GET ${URL}... "
            # -f = fail on 4xx/5xx response, -I = send HEAD request
            if curl -s -f -I "$URL" >/dev/null; then
              echo "OK"
            else
              echo "ERROR (unavailable: ${URL})"
              exit 1
            fi
          done

      - name: Tear down Docker Compose stack
        if: always()
        run: |
          echo "Cleaning up..."
          docker compose -f docker-compose.hk2025.yml down --volumes
