# .github/workflows/integration-tests.yml
name: Integration Tests (PoC)

on:
  push:
  pull_request:

jobs:
  integration-poc:
    name: Run the token test as integration PoC
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: testdb
        ports: ['5432:5432']

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set DEMO env for server
        run: echo "DEMO=True" >> $GITHUB_ENV

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Run only the token test
        run: pytest tests/test_token.py --maxfail=1 --disable-warnings -q
