name: Integration Tests

on:
  push:
  pull_request:

jobs:
  integration:
    name: Run integration suite
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports: ['5432:5432']
        # počkejte, až bude DB připravená
        options: >-
          --health-cmd="pg_isready -U postgres -d testdb"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=5

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set DEMO env for server
        run: echo "DEMO=True" >> $GITHUB_ENV

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Start Uvicorn server
        # spustíme na pozadí; port 8008 zvolíte podle environment.txt
        run: |
          uvicorn server.main:app \
            --host 0.0.0.0 \
            --port 8008 \
            --reload &  
          sleep 5

      - name: Run integration tests
        run: pytest tests/integration --maxfail=1 --disable-warnings -q