# .github/workflows/python-lint-only.yml
name: CI - Python Lint Only
#* working - but throws errors cuz bad formating and unused imports etc.
on:
  # push:
  #   branches: [ pipelines ]
  pull_request:
    branches: [ pipelines ]

jobs:
  python-lint:
    name: Flake8 linting (jen chyby “F”)
    runs-on: ubuntu-latest

    env:
      TZ: Europe/Prague

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8, select only “F” error codes
        run: |
          # Kontrola F-kódů (např. F401 unused-import, F821 undefined-name, apod.)
          # Ignorujeme všechny chyby E/E2/E3/W, abychom zatím neřešili formátování ani délku řádků.
          flake8 server/ tests/ --ignore=E,E2,E3,W --select=F || exit 1