name: Run test_token.py
#* working - but not enough pytests
on:
  push:
    #branches: [ latest ]
    #branches: [ main ]
  pull_request:
    #branches: [ latest ]
    branches: [ main ]

jobs:
  test-token:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-asyncio pytest-cov

      - name: Run only test_token.py
        run: pytest tests/test_token.py -q
