name: Unit Tests

on:
  push:
  pull_request:

jobs:
  test-token:
    name: Run test_token.py
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Run token unit test
        run: |
          pytest tests/test_token.py --maxfail=1 --disable-warnings -q
